# Generated by Django 5.0.3 on 2024-03-10 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_tasklist_task_current_time_tasklist_task_start_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklist',
            name='task_current_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='tasklist',
            name='task_start_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
