# Generated by Django 5.0.3 on 2024-03-10 21:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_tasklist_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklist',
            name='task_current_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
