# Generated by Django 5.0.3 on 2024-03-10 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_tasklist_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasklist',
            old_name='task',
            new_name='task_name',
        ),
    ]
