# Generated by Django 5.0.3 on 2024-03-12 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_rename_task_tasklist_task_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklist',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
