# Generated by Django 5.0.3 on 2024-03-12 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_tasklist_task_time_interval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklist',
            name='task_time_interval',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
