# Generated by Django 5.0.3 on 2024-04-03 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0020_rename_task_start_time_tasklist_creation_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasklist',
            options={'verbose_name': 'Список задач', 'verbose_name_plural': 'Список задач'},
        ),
        migrations.RemoveField(
            model_name='tasklist',
            name='task_time_interval',
        ),
    ]
