# Generated by Django 5.0.3 on 2024-04-09 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0023_remove_tasklist_task_current_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklist',
            name='active_task_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
