# Generated by Django 5.0.3 on 2024-03-10 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_tasklist_task_current_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklist',
            name='task_current_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
