# Generated by Django 5.0.3 on 2024-03-12 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_tasklist_is_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklist',
            name='task_current_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
