# Generated by Django 5.0.3 on 2024-03-12 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_alter_tasklist_task_current_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklist',
            name='task_current_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
