# Generated by Django 5.0.3 on 2024-03-12 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_alter_tasklist_task_current_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklist',
            name='completed_task_end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='tasklist',
            name='completed_task_start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
