# Generated by Django 5.0.3 on 2024-03-13 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0018_alter_tasklist_task_time_interval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklist',
            name='order',
            field=models.IntegerField(default=100000),
        ),
    ]
