# Generated by Django 5.0.3 on 2024-04-06 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0022_alter_tasklist_completed_task_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasklist',
            name='task_current_time',
        ),
    ]
